### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *I saw this app didn't pass CI, but it can't at the moment, you'll have to manually edit package_check to do the trick.*
- *It also has an issue with root install, the nginx config file looks weird to me, I don't understand how to fix this...*

## Solution
- *And how you fix that*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : Maniack C
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Josué
- [x] **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/agendav_ynh%20testing%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Ready to be checked

**Comment by maniackcrudelis** [comment]
Just tried the upgrade from the current version.
The upgrade works fine, but I have an "Internal server error" when I try to use Agendav.

**Comment by maniackcrudelis** [comment]
I just retried this app.
So, maybe I'm not lucky...

With the previous package or an upgrade from the old one to this one, I still have a "Internal server error".
With a new installation from this version of the package, my password is rejected. Seems there's a problem with ldap.

**Comment by Gofannon** [comment]
Do you need some help on testing this PR ?

@Rafi594 @maniackcrudelis

**Comment by maniackcrudelis** [comment]
Yes @Gofannon, some help would be welcome

**Comment by Gofannon** [comment]
@Jibec, feel free to go on working on this application and PR if you want/can. You seem to have done a lot already :)

I will not work on it in the meantime and have not checked what is needed to get it merge into `master`

**Comment by Jibec** [comment]
Well, I think only feedback is needed.
I won't spend any more time until it is requested.

**Comment by Gofannon** [comment]
@maniackcrudelis When you will have some time/energy, could you give some pointers please about what to do with this PR to @Jibec and I please?

**Comment by Jibec** [comment]
Just tried again, it works fine with x86_64.
I do reproduce the "Internal server error" when I don't disable ssl checks while using self-signed certificate. Which is the case when testing on a Virtual Machine.

This not explicit error message isn't an issue from the package.

When upgrading, if you test in a VM, you'll have the same internal issue, as default configuration checks certificate:
https://github.com/YunoHost-Apps/agendav_ynh/blob/testing/scripts/upgrade#L65
It's also what the software assumes: http://agendav.readthedocs.io/en/2.2.0/admin/configuration/?highlight=caldav.certificate.verify#confval-caldav.certificate.verify

Is this the issue you're facing?
Btw, logs are in /var/log/$app

**Comment by Jibec** [comment]
I'm fine with fixing this issue. I understand removing the CA check is fine (and remove the possibly from manifest).

Note this is a role and responsibility issue with official packages. I submitted a PR long ago to help improving the package and it was merged. I was responsible for answering requests and fixing bugs I added.

Here it's an internal process of packaging team, which I'm not part of.

**Comment by Gofannon** [comment]
There seems to be lots of trouble and history between the two of you. I leave this in your hands then. This is sad to see :(

I cannot do anything technically on this package to fix it.

**Comment by maniackcrudelis** [comment]
Eventually this PR works fine...
So, we can review it

**Comment by maniackcrudelis** [comment]
Upgrade from current version ok.
Will be merged in 3 days.

**Pull request merged**
