### PR TITLE
Upgrade to 2.2.1 - /!\ Requires YunoHost patch, please read only

### LINKED ISSUE #54: 2.2.0 is broken -timezone issue- please upgrade to 2.2.1+
### Describe the bug

There is an issue with the timezone on Agendav 2.2.0. Please Upgrade to 2.2.1+.

### Context

https://github.com/agendav/agendav/issues/272
https://github.com/agendav/agendav/releases/tag/2.2.1

### Steps to reproduce

In "Europe/Paris" timezone (see parameters) create an event on https://demo.yunohost.org/agendav/ for example, at 16:00.
The event is actually created at 17:00.

### Expected behavior

The event appears at 16:00.

### PR DESCRIPTION
**Pull request by nicofrand**
## Problem

- Fixes #54

## Solution

- Upgrade to 2.2.1

## PR Status

There remains an issue with EOL lines and this line must add `--binary` to the `patch` arguments: https://github.com/YunoHost/yunohost/blob/dev/data/helpers.d/utils#L222 (the files from the agendav archive use CRLF line endings and not LF anymore).

I don't know how to do that properly but I am opening this PR in the hope someone can help.

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by nicofrand** [comment]
TBH I only tested the upgrade on my server (which worked), so the "Upgrade" part should at least work :confused:

**Comment by ericgaspar** [comment]
!testme

**Comment by nicofrand** [comment]
This still requires a modification on the core (see description) that I did not have time to do yet.

**Comment by yalh76** [comment]
!testme

**Pull request closed without merging**
