### PR TITLE
2.4.0

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by nicofrand** [comment]
For what it's worth (ignore it if you don't care or are not interested, I should not have done it), even though the bot said there were lint failures I tried it on my server (2.2.0 being buggy) and got this:

```
# yunohost app upgrade agendav -u https://github.com/YunoHost-Apps/agendav_ynh/tree/2.4.0
Info: Now upgrading agendav...
Info: [....................] > Loading installation settings...
Info: [+...................] > Ensuring downward compatibility...
Info: [#++++++++...........] > Backing up AgenDAV before upgrading (may take a while)...
Info: [#########+..........] > Upgrading source files...0
Warning: Unable to apply patches
Warning: [Error] Upgrade failed.
```

https://paste.yunohost.org/raw/oqemaxukel

**Comment by nicofrand** [comment]
Answer to previous issue: 2.2.1 has now CRLF line endings whereas 2.2.0 had LF.
The `patch` command should ignore it but I don't know when/where that's applied.

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Pull request closed without merging**
