### PR TITLE
Fix installation on root

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Agendav doesn't work on root*
- *Test on root has been disable...*

## Solution
- *Revert those fucking commits !!! https://github.com/YunoHost-Apps/agendav_ynh/commit/6418e0fb579bc6725e523604cd23502cb8bc7045#diff-423e97862c462846d2e2b83cf15e218d and https://github.com/YunoHost-Apps/agendav_ynh/commit/aa5d2e8b987b0894b4fa512d7ff585e8a6d00c12#diff-2da33fb08900b413f2f199fe4ba4aa0f*
- Fix https://github.com/YunoHost-Apps/agendav_ynh/issues/28

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** :  Anmol
- [x] **Approval (LGTM)** : Anmol
- [x] **Approval (LGTM)** : Josué
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/agendav_ynh%20fix_root%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by nicofrand** [comment]
I am not a reviewer and can't tell for subpaths (there only was a commend added in this MR) but if that can help: on a root level that's what I did on my yunohost to prevent endless redirections :+1:.

**Comment by Josue-T** [comment]
Didn't tested. But look good.

**Comment by maniackcrudelis** [comment]
up

**Comment by anmol26s** [comment]
Ready to be merged.

**Pull request merged**
