### PR TITLE
Fix certificat issue

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Current testing doesn't work...*
- *There's an known issue with self signed certificates*
- *Stretch CI test doesn't work*
- *HTTP Auth is broken*

## Solution
- *Do not check the certificate, so do not fail with "Internal server error"*
- *Fix check_process pre_install command*
- *Restore patches for HTTP Auth...*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Josué
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/agendav_ynh%20fix_testing%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Review is OK for me. As PHP 5.6 security support will be dropped in December, I would strongly advise to require YunoHost 3.0.0 and spare our time on Jessie support in that particular case... :sweat_smile:

**Comment by maniackcrudelis** [comment]
It would be clearly also a solution to just set the requirement at ynh 3. Anyway, we're going to definitively give up jessie. Just I don't want to be too quick on this matter.

But, here, if no one has any other solution. It could be.
Still, I'm wondering why it works only on stretch. I think that it should be verified to be really sure it works as expected.

**Comment by JimboJoe** [comment]
One week passed with no other point of view... What about dropping Jessie support?
I personally don't see any reason for the patch to fail on Jessie... :thinking:

**Comment by maniackcrudelis** [comment]
I agree to give up jessie for this app.
But, it should be verified that the current fix really works on stretch.

**Comment by JimboJoe** [comment]
I've adapted the HTTP auth patch to the current version of agendav.
The application seems to be working as expected on Stretch.
Haven't tested on Jessie, though (no more server).

**Comment by maniackcrudelis** [comment]
Wonderful job \o/
It works perfectly on stretch, with ldap and http auth. But on Jessie, we still have a error with ldap which doesn't recognize the user.
So let's get rid of jessie for this app.

**Comment by Josue-T** [comment]
Will be merged in 3 days

**Pull request merged**
